# Generated by Django 5.1.4 on 2024-12-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendit_app', '0006_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
