# Generated by Django 5.1.4 on 2024-12-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendit_app', '0007_remove_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='sender',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('courier', 'Courier')], default='customer', max_length=15),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
