# Generated by Django 5.1.4 on 2024-12-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendit_app', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('courier', 'Courier')], default='customer', max_length=15),
        ),
    ]
