# Generated by Django 5.1.4 on 2024-12-23 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendit_app', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_shipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
